name: parallel_workflow
version: "1.0.0"
description: "A workflow example demonstrating parallel execution capabilities"

# Global configuration
config:
  base_dir: "."  # Current working directory

# Input configuration
inputs:
  path: "input/*.txt"  # Input path supporting glob patterns

# Workflow steps definition
steps:
  # Initial step - creates input data
  generate_data:
    container: "ubuntu:latest"
    command: >
      echo "This is sample data for analysis" > ${run_dir}/outputs/data.txt &&
      echo "1 2 3 4 5 6 7 8 9 10" > ${run_dir}/outputs/numbers.txt &&
      echo "apple banana cherry date elderberry" > ${run_dir}/outputs/fruits.txt
    resources:
      cpu: 1
      memory: "1G"
      time_limit: "5m"  # 5 minutes time limit
    after: []  # No dependencies

  # These three steps can run in parallel after generate_data
  count_words:
    container: "ubuntu:latest"
    command: "wc -w ${run_dir}/outputs/data.txt > ${run_dir}/outputs/word_count.txt"
    resources:
      cpu: 1
      memory: "1G"
      time_limit: "2m"  # 2 minutes time limit
    after: [generate_data]  # Depends on generate_data

  calculate_sum:
    container: "ubuntu:latest"
    command: >
      awk '{sum=0; for(i=1; i<=NF; i++) sum+=$i; print sum}' ${run_dir}/outputs/numbers.txt > ${run_dir}/outputs/sum.txt
    resources:
      cpu: 1
      memory: "1G"
      time_limit: "2m"  # 2 minutes time limit
    after: [generate_data]  # Depends on generate_data

  sort_fruits:
    container: "ubuntu:latest"
    command: "cat ${run_dir}/outputs/fruits.txt | tr ' ' '\\n' | sort > ${run_dir}/outputs/sorted_fruits.txt"
    resources:
      cpu: 1
      memory: "1G"
      time_limit: "2m"  # 2 minutes time limit
    after: [generate_data]  # Depends on generate_data

  # These two steps depend on the previous parallel steps
  count_chars:
    container: "ubuntu:latest"
    command: "wc -c ${run_dir}/outputs/word_count.txt > ${run_dir}/outputs/char_count.txt"
    resources:
      cpu: 1
      memory: "1G"
      time_limit: "1m"  # 1 minute time limit
    after: [count_words]  # Depends on count_words

  reverse_sort:
    container: "ubuntu:latest"
    command: "cat ${run_dir}/outputs/sorted_fruits.txt | sort -r > ${run_dir}/outputs/reverse_sorted_fruits.txt"
    resources:
      cpu: 1
      memory: "1G"
      time_limit: "1m"  # 1 minute time limit
    after: [sort_fruits]  # Depends on sort_fruits

  # Final step - combines results from all branches
  final_report:
    container: "ubuntu:latest"
    command: >
      echo "=== Parallel Workflow Report ===" > ${run_dir}/outputs/final_report.txt &&
      echo "Word count:" >> ${run_dir}/outputs/final_report.txt &&
      cat ${run_dir}/outputs/word_count.txt >> ${run_dir}/outputs/final_report.txt &&
      echo "Sum of numbers:" >> ${run_dir}/outputs/final_report.txt &&
      cat ${run_dir}/outputs/sum.txt >> ${run_dir}/outputs/final_report.txt &&
      echo "Sorted fruits:" >> ${run_dir}/outputs/final_report.txt &&
      cat ${run_dir}/outputs/sorted_fruits.txt >> ${run_dir}/outputs/final_report.txt &&
      echo "Character count:" >> ${run_dir}/outputs/final_report.txt &&
      cat ${run_dir}/outputs/char_count.txt >> ${run_dir}/outputs/final_report.txt
    resources:
      cpu: 1
      memory: "1G"
      time_limit: "3m"  # 3 minutes time limit
    after: [count_chars, calculate_sum, reverse_sort]  # Depends on multiple steps 