name: simple_workflow
version: "1.0.0"
description: "A simple workflow example for BioinfoFlow"

# Global configuration
config:
  base_dir: "."  # Current working directory

# Input configuration
inputs:
  path: "input/*.txt"  # Input path supporting glob patterns

# Workflow steps definition
steps:
  hello_world:
    container: "ubuntu:latest"
    command: "echo 'Hello, BioinfoFlow!' > ${run_dir}/outputs/hello.txt"
    resources:
      cpu: 1
      memory: "1G"
    after: []  # No dependencies

  count_words:
    container: "ubuntu:latest"
    command: "wc -w ${run_dir}/outputs/hello.txt > ${run_dir}/outputs/word_count.txt"
    resources:
      cpu: 1
      memory: "1G"
    after: [hello_world]  # Depends on hello_world step

  final_report:
    container: "ubuntu:latest"
    command: >
      cat ${run_dir}/outputs/hello.txt ${run_dir}/outputs/word_count.txt > ${run_dir}/outputs/final_report.txt
    resources:
      cpu: 1
      memory: "1G"
    after: [count_words]  # Depends on previous steps 